topics:
  # Structure and Bonding
  - code: "S1.1"
    name: "Introduction to the particulate nature of matter"
    category: "S1. Structure"
  - code: "S1.2"
    name: "The nuclear atom"
    category: "S1. Structure"
  - code: "S1.3"
    name: "Electron configurations"
    category: "S1. Structure"
  - code: "S1.4"
    name: "Counting particles by mass: The mole"
    category: "S1. Structure"
  - code: "S1.5"
    name: "Ideal gases"
    category: "S1. Structure"
  - code: "S2.1"
    name: "The ionic model"
    category: "S2. Models of Bonding"
  - code: "S2.2"
    name: "The covalent model"
    category: "S2. Models of Bonding"
  - code: "S2.3"
    name: "The metallic model"
    category: "S2. Models of Bonding"
  - code: "S2.4"
    name: "From models to materials"
    category: "S2. Models of Bonding"
  - code: "S3.1"
    name: "The periodic table: Classification of elements"
    category: "S3. Classification of Matter"
  - code: "S3.2"
    name: "Functional groups: Classification of organic compounds"
    category: "S3. Classification of Matter"

  # Reactivity
  - code: "R1.1"
    name: "Measuring enthalpy changes"
    category: "R1. Energy and Chemical Change"
  - code: "R1.2"
    name: "Energy cycles in reactions"
    category: "R1. Energy and Chemical Change"
  - code: "R1.3"
    name: "Energy from fuels"
    category: "R1. Energy and Chemical Change"
  - code: "R1.4"
    name: "Entropy and spontaneity"
    category: "R1. Energy and Chemical Change"
  - code: "R2.1"
    name: "How much? The amount of chemical change"
    category: "R2. Stoichiometry"
  - code: "R2.2"
    name: "How fast? The rate of chemical change"
    category: "R2. Stoichiometry"
  - code: "R2.3"
    name: "How far? The extent of chemical change"
    category: "R2. Stoichiometry"
  - code: "R3.1"
    name: "Proton transfer reactions"
    category: "R3. Types of Reactions"
  - code: "R3.2"
    name: "Electron transfer reactions"
    category: "R3. Types of Reactions"
  - code: "R3.3"
    name: "Electron sharing reactions"
    category: "R3. Types of Reactions"
  - code: "R3.4"
    name: "Electron-pair sharing reactions"
    category: "R3. Types of Reactions"

  # Tools and Techniques
  - code: "T1"
    name: "Experimental techniques"
    category: "Tools"
  - code: "T2"
    name: "Instrumentation"
    category: "Tools"
  - code: "T3"
    name: "Spectroscopic identification of organic compounds"
    category: "Tools"


