topics:
  - code: "A.1"
    name: "Kinematics"
    category: "A. Space, Time, and Motion"
  - code: "A.2"
    name: "Forces and momentum"
    category: "A. Space, Time, and Motion"
  - code: "A.3"
    name: "Work, energy and power"
    category: "A. Space, Time, and Motion"
  - code: "A.4"
    name: "Rigid body mechanics"
    category: "A. Space, Time, and Motion"
  - code: "A.5"
    name: "Galilean and special relativity"
    category: "A. Space, Time, and Motion"
  - code: "B.1"
    name: "Thermal energy transfers"
    category: "B. The Particulate Nature of Matter"
  - code: "B.2"
    name: "Modelling a gas"
    category: "B. The Particulate Nature of Matter"
  - code: "B.3"
    name: "Thermodynamics"
    category: "B. The Particulate Nature of Matter"
  - code: "B.4"
    name: "Thermal energy transfer"
    category: "B. The Particulate Nature of Matter"
  - code: "B.5"
    name: "Current and circuits"
    category: "B. The Particulate Nature of Matter"
  - code: "C.1"
    name: "Simple harmonic motion"
    category: "C. Wave Behaviour"
  - code: "C.2"
    name: "Wave model"
    category: "C. Wave Behaviour"
  - code: "C.3"
    name: "Wave phenomena"
    category: "C. Wave Behaviour"
  - code: "C.4"
    name: "Standing waves and resonance"
    category: "C. Wave Behaviour"
  - code: "C.5"
    name: "Doppler effect"
    category: "C. Wave Behaviour"
  - code: "D.1"
    name: "Gravitational fields"
    category: "D. Fields"
  - code: "D.2"
    name: "Electric and magnetic fields"
    category: "D. Fields"
  - code: "D.3"
    name: "Motion in electromagnetic fields"
    category: "D. Fields"
  - code: "D.4"
    name: "Electromagnetic induction"
    category: "D. Fields"
  - code: "D.5"
    name: "Power generation and transmission"
    category: "D. Fields"
  - code: "E.1"
    name: "Structure of the atom"
    category: "E. Nuclear and Quantum Physics"
  - code: "E.2"
    name: "Quantum physics"
    category: "E. Nuclear and Quantum Physics"
  - code: "E.3"
    name: "Radioactive decay"
    category: "E. Nuclear and Quantum Physics"
  - code: "E.4"
    name: "Fission"
    category: "E. Nuclear and Quantum Physics"
  - code: "E.5"
    name: "Fusion and stars"
    category: "E. Nuclear and Quantum Physics"

